#!/bin/bash


sudo apt-get -y update                                                                 #Actualizar el sistema operativo y los repositorios:

sudo apt-get -y upgrade

sudo apt-get -y install apache2                                                        #Instalar el servicio de Apache2

sudo apt-get -y install php5                                                           #Instalar php5

sudo apt-get -y install php5-mysql                                                     #Instalar php mysql

sudo apt-get -y install mysql-server                                                                #(colocar la contraseña)

sudo apt-get -y install apache2 phpmyadmin                                                     #Instalar phpmyadmin

#Colocar la contraseña de mysql-server para el usuario root de phpmyadmin
