#!/bin/bash


$ echo "y" | sudo apt-get update                                                                 #Actualizar el sistema operativo y los repositorios:

$ echo "y" | sudo apt-get upgrade

$ echo "y" | sudo apt-get install apache2                                                        #Instalar el servicio de Apache2

$ echo "y" | sudo apt-get install php5                                                           #Instalar php5

$ echo "y" | sudo apt-get install php5-mysql                                                     #Instalar php mysql

sudo apt-get install mysql-server                                                                #(colocar la contraseña)

$ echo "y" | sudo apt-get install phpmyadmin                                                     #Instalar phpmyadmin

#Colocar la contraseña de mysql-server para el usuario root de phpmyadmin
